### ISSUE TITLE
多线程没有性能提升

### ISSUE THREAD

**Issue by ycfung** [LinRayx/multithreading_of_nqueen#1]
在ubuntu下使用g++和-lpthread参数进行编译，测试更改ThreadPool的构造参数为1-8，可以观察到线程数大于1时CPU的使用有分散，但是无论线程数为多少，最终运行的时间基本没有差异（萌新瑟瑟发抖

**Comment by LinRayx** [comment]
不好意思，我的锅，我代码上传错了，这个原因我readme里面解释了，我之前的写法，直接get()的话就和单线程没有区别了。

**Comment by ycfung** [comment]
😏感谢大佬的回复，我也得重新捡起cpp好好研究一下了
